### ISSUE TITLE
Radar Cutoff & Project date-time submission

### ISSUE THREAD

**Issue by IliaMaz** [micheldrescher/cw-project-radar#23]
People submitting `projects|mtrl|classifications` ±1 hour to midnight can hit a bug with the Radar cutoff date. We need to ensure that this doesn't happen.

**Comment by micheldrescher** [comment]
Requires investigation into the library `moments.js`

**Comment by micheldrescher** [comment]
Closing as relevant only in testing conditions that submit MTRL scores in rapid succession (i.e. < 1s resolution).
