### ISSUE TITLE
Production Radar Version Number

### ISSUE THREAD

**Issue by IliaMaz** [micheldrescher/cw-project-radar#24]
The production version of the radar fails to visualize the version number from the `package.json`:

For reference, view: http://cradar.cyberwatching.eu/

**Comment by micheldrescher** [comment]
The Dockerfile for the node image starts the server differently than in production mode. This does not expose an process-scoped env var the display of the version number depends on.

**Comment by micheldrescher** [comment]
Fixed in commit 0b20f7e
