### ISSUE TITLE
Suggestion: Delete all filters button

### ISSUE THREAD

**Issue by Malinche77** [micheldrescher/cw-project-radar#27]
It would be useful to add a "Delete all filters" button.

**Comment by micheldrescher** [comment]
Good idea, will work on that.

Where specifically do you suggest the "Clear" button to be placed?

**Comment by Malinche77** [comment]
I would say within the JRC taxonomy filter box, together with Apply, Cancel and then "clear all".

**Comment by micheldrescher** [comment]
Implemented in commit bcafd85
