### ISSUE TITLE
JRC filters don't work in a segment view

### ISSUE THREAD

**Issue by Malinche77** [micheldrescher/cw-project-radar#28]
I've tried in live radar with Secure Systems segment and clicking all the sectors in the JRC filter, and the segment is empty of projects.

**Comment by micheldrescher** [comment]
You can specify the way the selected tags are applied:
* **all** tags must be present in the project for it to be shown, or
* **any** of the tags in the filter must be present in the project for it to be shown.

Have you tried these radio buttons?

**Comment by Malinche77** [comment]
Ok, now I see the problem. In the live radar, there is only one project with a tag 262.COLSOC dev test. Applying the filter for this project, it works, in the main radar and in the segment.

**Comment by Malinche77** [comment]
Ups! COLSOC is a test project! I see now...
