### ISSUE TITLE
The word "median" overlaps maximum score if they have the same value in "relative performance" in "Spring 2020" edition

### ISSUE THREAD

**Issue by Malinche77** [micheldrescher/cw-project-radar#32]
In "Spring 2020" edition, in segment "Identity & Privacy", when I select and open the info for PAPAYA, OLYMPUS or BPR4GDPR, I can't see the maximum score of "reative performance" because the word "median" is over it.

**Comment by micheldrescher** [comment]
Fixed in commit da93c65a
