### ISSUE TITLE
'Blip' view rotation

### ISSUE THREAD

**Issue by DCHW75** [micheldrescher/cw-project-radar#41]
Hi,

When using this on Safari then for the lower sectors when you expand them and they rotate into 'icecream cone' view the orientation of the numbering in each blip doesn;t chang nd they can end up upside down.

David

**Comment by micheldrescher** [comment]
Safari supports the CSS3 property `transform: rotate(adeg);` which is used here. However, the property is used on SVG elements, not HTML elements in the Radar application.

SVG2 mandates that CSS3 properties may be used on SVG elements. Safari, however, only implements SVG1.1 fully where CSS3 properties on SVG are not supported.

Manual testing using the SVG transform attribute(!) `transform="rotate(a)" (note the different syntax) works with Safari. 

Having both, i.e. the CSS3 property as well as the SVG1.1 attribute in the HTML document at the same time does not affect the outcome in either Firefox, Safari, or Chrome.
